// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.3
// source: avia.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TicketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string               `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   string               `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Data *timestamp.Timestamp `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TicketRequest) Reset() {
	*x = TicketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_avia_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketRequest) ProtoMessage() {}

func (x *TicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avia_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketRequest.ProtoReflect.Descriptor instead.
func (*TicketRequest) Descriptor() ([]byte, []int) {
	return file_avia_proto_rawDescGZIP(), []int{0}
}

func (x *TicketRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TicketRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TicketRequest) GetData() *timestamp.Timestamp {
	if x != nil {
		return x.Data
	}
	return nil
}

type TicketResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DepTime  *timestamp.Timestamp `protobuf:"bytes,2,opt,name=depTime,proto3" json:"depTime,omitempty"`
	Duration int64                `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Price    int64                `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *TicketResponce) Reset() {
	*x = TicketResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_avia_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketResponce) ProtoMessage() {}

func (x *TicketResponce) ProtoReflect() protoreflect.Message {
	mi := &file_avia_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketResponce.ProtoReflect.Descriptor instead.
func (*TicketResponce) Descriptor() ([]byte, []int) {
	return file_avia_proto_rawDescGZIP(), []int{1}
}

func (x *TicketResponce) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TicketResponce) GetDepTime() *timestamp.Timestamp {
	if x != nil {
		return x.DepTime
	}
	return nil
}

func (x *TicketResponce) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TicketResponce) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_avia_proto protoreflect.FileDescriptor

var file_avia_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x61, 0x76, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x76,
	0x69, 0x61, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x0d, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x2e,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x88,
	0x01, 0x0a, 0x0e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x34, 0x0a, 0x07, 0x64, 0x65, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07,
	0x64, 0x65, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x32, 0x55, 0x0a, 0x0b, 0x41, 0x76, 0x69,
	0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x41, 0x76, 0x69, 0x61,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x61, 0x76, 0x69, 0x61, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x76, 0x69, 0x61, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x30, 0x01,
	0x42, 0x15, 0x5a, 0x13, 0x61, 0x76, 0x69, 0x61, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x61, 0x76, 0x69, 0x61, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_avia_proto_rawDescOnce sync.Once
	file_avia_proto_rawDescData = file_avia_proto_rawDesc
)

func file_avia_proto_rawDescGZIP() []byte {
	file_avia_proto_rawDescOnce.Do(func() {
		file_avia_proto_rawDescData = protoimpl.X.CompressGZIP(file_avia_proto_rawDescData)
	})
	return file_avia_proto_rawDescData
}

var file_avia_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_avia_proto_goTypes = []interface{}{
	(*TicketRequest)(nil),       // 0: aviaapi.v1.TicketRequest
	(*TicketResponce)(nil),      // 1: aviaapi.v1.TicketResponce
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_avia_proto_depIdxs = []int32{
	2, // 0: aviaapi.v1.TicketRequest.data:type_name -> google.protobuf.Timestamp
	2, // 1: aviaapi.v1.TicketResponce.depTime:type_name -> google.protobuf.Timestamp
	0, // 2: aviaapi.v1.AviaService.AviaTickets:input_type -> aviaapi.v1.TicketRequest
	1, // 3: aviaapi.v1.AviaService.AviaTickets:output_type -> aviaapi.v1.TicketResponce
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_avia_proto_init() }
func file_avia_proto_init() {
	if File_avia_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_avia_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_avia_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_avia_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_avia_proto_goTypes,
		DependencyIndexes: file_avia_proto_depIdxs,
		MessageInfos:      file_avia_proto_msgTypes,
	}.Build()
	File_avia_proto = out.File
	file_avia_proto_rawDesc = nil
	file_avia_proto_goTypes = nil
	file_avia_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AviaServiceClient is the client API for AviaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AviaServiceClient interface {
	AviaTickets(ctx context.Context, in *TicketRequest, opts ...grpc.CallOption) (AviaService_AviaTicketsClient, error)
}

type aviaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAviaServiceClient(cc grpc.ClientConnInterface) AviaServiceClient {
	return &aviaServiceClient{cc}
}

func (c *aviaServiceClient) AviaTickets(ctx context.Context, in *TicketRequest, opts ...grpc.CallOption) (AviaService_AviaTicketsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AviaService_serviceDesc.Streams[0], "/aviaapi.v1.AviaService/AviaTickets", opts...)
	if err != nil {
		return nil, err
	}
	x := &aviaServiceAviaTicketsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AviaService_AviaTicketsClient interface {
	Recv() (*TicketResponce, error)
	grpc.ClientStream
}

type aviaServiceAviaTicketsClient struct {
	grpc.ClientStream
}

func (x *aviaServiceAviaTicketsClient) Recv() (*TicketResponce, error) {
	m := new(TicketResponce)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AviaServiceServer is the server API for AviaService service.
type AviaServiceServer interface {
	AviaTickets(*TicketRequest, AviaService_AviaTicketsServer) error
}

// UnimplementedAviaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAviaServiceServer struct {
}

func (*UnimplementedAviaServiceServer) AviaTickets(*TicketRequest, AviaService_AviaTicketsServer) error {
	return status.Errorf(codes.Unimplemented, "method AviaTickets not implemented")
}

func RegisterAviaServiceServer(s *grpc.Server, srv AviaServiceServer) {
	s.RegisterService(&_AviaService_serviceDesc, srv)
}

func _AviaService_AviaTickets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TicketRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AviaServiceServer).AviaTickets(m, &aviaServiceAviaTicketsServer{stream})
}

type AviaService_AviaTicketsServer interface {
	Send(*TicketResponce) error
	grpc.ServerStream
}

type aviaServiceAviaTicketsServer struct {
	grpc.ServerStream
}

func (x *aviaServiceAviaTicketsServer) Send(m *TicketResponce) error {
	return x.ServerStream.SendMsg(m)
}

var _AviaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aviaapi.v1.AviaService",
	HandlerType: (*AviaServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AviaTickets",
			Handler:       _AviaService_AviaTickets_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "avia.proto",
}
